version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_salonline
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8003:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:VoeBoZehg9GD/w87qME1HqvLJnR6s/DECoJYShTwuJI=
      - APP_URL=http://localhost:8003
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db_salonline
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3003:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: